name: Code checks

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql-service:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db_test
        ports:
          - 33306:3306
        # Set health checks to wait until mysql database has started (it takes some seconds to start)
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Write ssh key to enable composer authentication for prive whilesmart packages
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TEST_BACKEND_SSHKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Copy environment variables
        run: php -r "file_exists('workbench/.env') || copy('workbench/.env.example', 'workbench/.env');"
      - name: Update .env file
        run: |
          echo "DB_CONNECTION=mysql" >> workbench/.env
          echo "DB_HOST=127.0.0.1" >> workbench/.env
          echo "DB_PORT=33306" >> workbench/.env
          echo "DB_DATABASE=db_test" >> workbench/.env
          echo "DB_USERNAME=root" >> workbench/.env
          echo "DB_PASSWORD=password" >> workbench/.env
          echo "APP_ENV=testing" >> workbench/.env
      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Run migrations
        run: vendor/bin/testbench migrate
      - name: Run tests
        run: vendor/bin/testbench package:test
      - name: Run linter test
        run: composer pint:test
      - name: Clean up SSH key
        if: always()
        run: rm -f ~/.ssh/id_rsa
